language: python
  - "3.5"
install: source travis-setup.sh
before_script:
  - export PATH=~/anaconda/bin:$PATH
script:
  - which python
  - python -c 'import sramongo; print(sramongo.__file__)'
  - which mongod
  - mongod --version
  - pytest -v tests
