language: python
  - "3.5"
install: bash travis-setup.sh
before_script:
  - export PATH=~/anaconda/bin:$PATH
addons:
  apt:
    - mongodb
script:
  - which python
  - python -c 'import sramongo; print(sramongo.__file__)'
  - pytest -v tests/
