language: python
  - "3.5"
sudo: required
install: bash travis-setup.sh
before_script:
  - export PATH=~/anaconda/bin:$PATH
addons:
  apt:
    - libssl1.0.0
    - libssl-dev
script:
  - which python
  - python -c 'import sramongo; print(sramongo.__file__)'
  - mongod --dbpath /tmp/db
